version: '3'
services:
  url_pairs_db:
    image: postgres:10.5
    container_name: url_pairs_db
    ports:
      - 5432:5432
    volumes: 
      - ./backend/internal/sql/url_pairs:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: postgres
    restart: always
  user_session_db:
    image: postgres:10.5
    container_name: user_session_db
    ports:
      - 5433:5432
    volumes: 
      - ./backend/internal/sql/user_session:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: postgres
    restart: always
  app1:
    image: golang:latest
    container_name: app1
    ports:
      - 8081:80
    volumes: 
      - .:/go/src/app
    depends_on: 
      - url_pairs_db
      - user_session_db
    working_dir: /go/src/app
    command: ["go", "run", "./backend/."]
  app2:
    image: golang:latest
    container_name: app2
    ports:
      - 8082:80
    volumes: 
      - .:/go/src/app
    depends_on: 
      - url_pairs_db
      - user_session_db
    working_dir: /go/src/app
    command: ["go", "run", "./backend/."]
  nginx:
    image: nginx:1.15
    ports:
      - "8080:80"
    volumes:
      - ./backend/internal/nginx/http.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
